# Generated by Django 2.0.3 on 2019-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=4096)),
                ('link', models.CharField(max_length=256)),
            ],
        ),
    ]
